apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  type: ClusterIP
  selector:
    app: pi-hole
  ports:
  - name: pi-hole-http
    protocol: TCP
    port: 80
    targetPort: 80 # must match containerPort in pod
  - name: pi-hole-https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pi-hole
spec:
  type: LoadBalancer # ‚Üê MetalLB assigns 192.168.4.201
  loadBalancerIP: 192.168.4.201
  selector:
    app: pi-hole
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
