apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.4.201 # Must be within the Metallb pool range
  selector:
    # Must match pod labels
    app: pi-hole
  ports:
  - name: pi-hole-http
    protocol: TCP
    port: 80
    targetPort: 80 # must match containerPort in pod
  - name: pi-hole-https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: pi-hole-dns-tcp
    targetPort: 53 # must match containerPort in pod
    protocol: TCP
    port: 53
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
