apiVersion: v1
kind: Secret
metadata:
  name: traefik-selfsigned-tls
  namespace: traefik
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""

# Traefik will automatically generate a self-signed certificate at runtime if none is provided. This empty secret instructs Kubernetes to allow Traefik to store/rotate it.
