apiVersion: v1
data:
  ca.json: |-
    {
        "root": "/home/step/certs/root_ca.crt",
        "federateRoots": [],
        "crt": "/home/step/certs/intermediate_ca.crt",
        "key": "/home/step/secrets/intermediate_ca_key",
        "address": "0.0.0.0:9000",
        "dnsNames": [
            "step-certificates.step-ca.svc.cluster.local"
        ],
        "logger": {
            "format": "json"
        },
        "db": {
            "type": "badgerv2",
            "dataSource": "/home/step/db"
        },
        "authority": {
            "enableAdmin": false,
            "provisioners": [
                {
                    "type": "JWK",
                    "name": "spar@smallstep.com",
                    "key": {
                        "use": "sig",
                        "kty": "EC",
                        "kid": "eNNMEWqxwD-h5bqBsTdgnS0I4MtJ7mWrpOUP0JRCSTw",
                        "crv": "P-256",
                        "alg": "ES256",
                        "x": "GDNXxPweFi9zIhMZcVhJ0bGuanGwwYLyqvrPJ75vaSE",
                        "y": "8tKuh0k-tjTXVBQTRcJcZ6PVJjb-mKHMUxt4Y8AsP3I"
                    },
                    "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoicTNrQVI0M2pGOVMxajhiTnZxbEd3USJ9.9bEvgDnZs_2bJb7WZgGZxmmht0kpifu-T4hlngbuTEAjFDSH_Gt-zA.ZGIfAAjWTH9MRtMb.kZoM9LfTh_Cf8PCJTkIg_8uta3rJNBqcKy1Q4jilrZ6A7c4RZPZ1Aw4NsniU19kgYQhFZD-c5qkaUkOnafbM3LGcQ4Gfta1456StoN8QvlHxoU9YTRUOw7j-5Ms6PnXB0IvteHe3b-iPTKUaj_k0pwxc3br1cVoo9Pk5NAEWbUou_inhCkkdW30aSC0JCN9peKc0_dBCh9H4-buTDVO0nDFQqgEW2KeOWGSZzzeHSoiA5DB9cnLMJRx-VLc68Z7ctdPxMeupfhgaJ4Fv00a6fw8gNqgjkQ2_xQiYAipsKRBPMUY7OCgxlNRYnNlEIrjC0BfzSg5zYGQYk_0aBYY.6ABJ33MJDahsa-bAF8a9sQ",
                    "options": {
                        "x509": {},
                        "ssh": {}
                    }
                }
            ]
        },
        "tls": {
            "cipherSuites": [
                "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
            ],
            "minVersion": 1.2,
            "maxVersion": 1.3,
            "renegotiation": false
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: step-certificates-config
  namespace: step-ca
